services:
  - type: web
    name: zone-xiv-directory
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false # Prompts the user for the connection string during deployment
